# Site settings
title: DasLab
email: rhiju@stanford.edu
description: ""
baseurl: ""
url: "http://daslab.github.io"
github_username:  daslab

# Build settings
markdown: kramdown
permalink: pretty

# Default variables
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      level: 1
      author: "Siqi Tian"
  -
    scope:
      path: "biers"
    values:
      title: "Biers"
      description: "<u>B</u>est <u>I</u>nference <u>E</u>ngine for <u>R</u>NA <u>S</u>tructure"
      repo: "DasLab/Biers"
      root: "/biers/"
  -
    scope:
      path: "lifft"
    values:
      title: "LIFFT"
      description: "<u>LI</u>kelihood-Based <u>F</u>its of <u>F</u>olding <u>T</u>ransitions"
      repo: "DasLab/LIFFT"
      root: "/lifft/"
  -
    scope:
      path: "map_seeker"
    values:
      title: "MAPseeker"
      description: "<u>M</u>ultiplexed <u>A</u>ccessibility <u>P</u>robing through Next Generation <u>Seq</u>uencing"
      repo: "DasLab/MAPseeker"
      root: "/map_seeker/"

# Markdown Processors
kramdown:
  input: GFM

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
