# Site settings
title: DasLab
email: rhiju@stanford.edu
description: ""
baseurl: ""
url: "http://daslab.github.io"
github_username:  daslab

# Build settings
markdown: kramdown
permalink: pretty

# Default variables
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      level: 1
      title: 
      author: "Siqi Tian"
      ga_tracker: UA-36037648-4
  -
    scope:
      path: "biers"
    values:
      title: "Biers"
      description: "<u>B</u>est <u>I</u>nference <u>E</u>ngine for <u>R</u>NA <u>S</u>tructure"
      repo: "DasLab/Biers"
      root: "/Biers/"

# Markdown Processors
kramdown:
  input: GFM

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         4
  #   coderay_bold_every:        10
  #   coderay_css:               style
